/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedGameResponse {
  genre?: string;
  id?: number;
  platform?: string;
  rate?: number;
  returnApproved?: boolean;
  returned?: boolean;
  title?: string;
}
