/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GameResponse {
  archived?: boolean;
  cover?: string;
  description?: string;
  genre?: string;
  id?: number;
  language?: string;
  owner?: string;
  platform?: string;
  rate?: number;
  shareable?: boolean;
  studio?: string;
  title?: string;
}
