/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GameRequest {
  description: string;
  genre: string;
  id?: number;
  language: string;
  platform: string;
  shareable?: boolean;
  studio: string;
  title: string;
  ownerName: string;
}
