/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { BorrowedGameResponse } from './models/borrowed-game-response';
export { FeedbackRequest } from './models/feedback-request';
export { FeedbackResponse } from './models/feedback-response';
export { GameRequest } from './models/game-request';
export { GameResponse } from './models/game-response';
export { PageResponseBorrowedGameResponse } from './models/page-response-borrowed-game-response';
export { PageResponseFeedbackResponse } from './models/page-response-feedback-response';
export { PageResponseGameResponse } from './models/page-response-game-response';

