/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { GameService } from './services/game.service';
export { FeedbackService } from './services/feedback.service';
